/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xieweizhong' at '18-1-10 下午2:36' with Gradle 2.14.1
 *
 * @author xieweizhong, @date 18-1-10 下午2:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
